# Site settings
title: Squeak/Smalltalk
copyright: Squeak Deutschland e.V.
url: https://squeak.de

# SEO
author: Squeak Deutschland e.V.
description: >-
  Squeak ist eine moderne, freie, und quelloffene Programmierumgebung für die Sprache Smalltalk.
twitter:
  username: squeaksmalltalk
logo: /static/img/squeak.png
social:
  name: Squeak Deutschland e.V.
  links:
    - https://twitter.com/squeaksmalltalk
    - https://github.com/squeak-smalltalk
    - https://www.linkedin.com/groups/98736

collections:
  # Order matters
  about:
    title: Squeak
    sort_by: order
    trailer: center
  downloads:
    title: Herunterladen
    sort_by: order
    hidden: true
  education:
    title: Bildung und Lehre
    sort_by: order
  squeakev:
    title: Squeak e.V.
    sort_by: order

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      cols: 6
      href-external: true
  -
    scope:
      path: ""
      type: "news"
    values:
      cols: 12
  -
    scope:
      path: ""
      type: "squeakev"
    values:
      cols: 12
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# Enable SASS support
sass:
  sass_dir: _sass
  style: :compressed

# Serving
host: 0.0.0.0

# Outputting
permalink: news/:year/:month/:day/:title/

# Caching
build_version: 1.2
staticurl: static/

# Build settings
highlighter: pygments
markdown: kramdown

# Filtering Content
future: true

# Enable plugins
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

include: [_pages]

# Exclude vendor dir which Travis uses to bundle all gems on its build servers
exclude: [vendor, README.md, LICENSE.md, Gemfile, Gemfile.lock, Rakefile, .jekyll-metadata]
